name: Update PyPi package

on:
  push:
      branches:
        - master

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: casperdcl/deploy-pypi@v1
        if: github.event_name == 'push'
        with:
          password: ${{ secrets.pypi_token }}
          build: true